import { getSession } from "@auth0/nextjs-auth0";
import LoginToAccess from "../../../../../components/noAccess/loginToAccess";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getSession();

  if (!session) {
    return <LoginToAccess />;
  }
  return <main>{children}</main>;
}
