// import { cookies } from "next/headers";
import AdminNav from "../../../components/Admin/adminNav";
import "../../../styles/index.scss";
// import { AUTH_COOKIE_KEY } from "../../../constants";
// import { redirect } from "next/navigation";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const cookieStore = cookies();

  // const cookie = cookieStore.get(AUTH_COOKIE_KEY);

  // if(!cookie) {
  //   redirect('/login')
  // }
  return (
    <html lang="en">
      <body>
        <div className="admin-layout">
          <h1>Admin Panel</h1>
          <div className="admin-navigation">
            <AdminNav />
            <main>{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
