import { redirect } from "next/navigation";
import "../../../styles/index.scss";
import { cookies } from "next/headers";
import { AUTH_COOKIE_KEY } from "../../../constants";
import { revalidatePath } from "next/cache";

interface RootLayoutProps {
  children: React.ReactNode;
}

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: RootLayoutProps) {
  const cookieStore = cookies();

  const cookie = cookieStore.get(AUTH_COOKIE_KEY);

  if (cookie) {
    redirect("/");
  }

  revalidatePath("/login");
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
